export const GAME_PLAYED="GAME_PLAYED";
export const TOTAL_SCORE="TOTAL_SCORE";
export const CONSISTENCY_AVERGE="CONSISTENCY_AVERGE";
export const SITE_CONSISTENCY_AVERGE="SITE_CONSISTENCY_AVERGE";
export const DEVIENCE_AVERGE="DEVIENCE_AVERGE";
export const SITE_DEVIENCE_AVERGE="SITE_DEVIENCE_AVERGE";
export const RANKING="RANKING";